item {
    id: 1
    name: 'day_motorcycle_front'
}

item {
    id: 2
    name: 'day_motorcycle_rear'
}

item {
    id: 3
    name: 'day_small_front'
}

item {
    id: 4
    name: 'day_small_rear'
}

item {
    id: 5
    name: 'day_small_truck_front'
}

item {
    id: 6
    name: 'day_small_truct_front'
}

item {
    id: 7
    name: 'day_truck_front'
}

item {
    id: 8
    name: 'day_truck_rear'
}

item {
    id: 9
    name: 'plate'
}